#!/bin/bash
# Coolify + open.unippc24.com 配置指南

echo "=========================================="
echo "🌐 Coolify 域名配置指南"
echo "=========================================="
echo ""

echo "目标: 让 open.unippc24.com 访问 control-center"
echo ""

echo "=========================================="
echo "📋 当前状态"
echo "=========================================="
echo ""
echo "Control Center 运行:"
ss -tlnp | grep 9091 || echo "  ⚠️  9091 未监听"
echo ""

echo "当前 .env 配置:"
grep "OPENCLAW_CONTROL_UI_URL" /data/openclaw-control-center/.env
echo ""

echo "=========================================="
echo "🔧 Coolify 配置步骤"
echo "=========================================="
echo ""

echo "步骤 1: 在 Coolify Dashboard 中"
echo "-------------------------------------------"
echo "1. 找到你的项目 (openclaw-control-center 或相关服务)"
echo "2. 进入 Settings / Domains"
echo "3. 添加域名: open.unippc24.com"
echo "4. 确保端口映射: 80/443 → 9091"
echo ""

echo "步骤 2: 更新 .env 配置"
echo "-------------------------------------------"
echo "运行以下命令:"
echo ""
echo "cd /data/openclaw-control-center"
echo "sed -i 's|OPENCLAW_CONTROL_UI_URL=.*|OPENCLAW_CONTROL_UI_URL=https://open.unippc24.com/|' .env"
echo ""
echo "# 同时添加信任代理设置（用于 HTTPS）"
echo "echo 'TRUST_PROXY=true' >> .env"
echo ""

echo "步骤 3: 重启服务"
echo "-------------------------------------------"
echo "pkill -f 'dev:ui'"
echo "npm run dev:ui"
echo ""

echo "=========================================="
echo "⚠️  关键问题: HTTPS 和 Gateway 连接"
echo "=========================================="
echo ""
echo "问题 1: HTTPS 下的 Gateway WebSocket"
echo "-------------------------------------------"
echo "当前 Gateway: ws://127.0.0.1:18789 (非加密)"
echo "Coolify HTTPS: wss:// (加密)"
echo ""
echo "浏览器会阻止 '混合内容' (HTTPS 页面连 WS)"
echo ""
echo "解决方案:"
echo "A) Gateway 也走 HTTPS (wss://)"
echo "B) 配置 Coolify 允许混合内容 (不推荐)"
echo "C) 使用 Nginx 代理 WebSocket"
echo ""

echo "问题 2: Gateway 可访问性"
echo "-------------------------------------------"
echo "当前 Gateway 只在 localhost:18789"
echo "Coolify 容器可能无法访问 VPS 的 localhost"
echo ""
echo "需要确认:"
echo "  - Coolify 和 control-center 在同一台 VPS?"
echo "  - Gateway 是否绑定 0.0.0.0:18789?"
echo ""

echo "=========================================="
echo "🚀 快速测试方案"
echo "=========================================="
echo ""
echo "先测试 HTTP (非 HTTPS):"
echo ""
echo "1. Coolify 配置域名指向 9091"
echo "2. 访问 http://open.unippc24.com/"
echo "3. 检查是否能看到界面"
echo ""
echo "如果看到界面但 Gateway 离线 → WebSocket 问题"
echo "如果连不上 → 端口/域名配置问题"
echo ""

echo "=========================================="
echo "❓ 需要你确认"
echo "=========================================="
echo ""
echo "1. Coolify 和 control-center 在同一台 VPS 吗?"
echo "2. 你的 OpenClaw Gateway 在哪里运行?"
echo "   - 同一台 VPS?"
echo "   - 不同机器?"
echo "   - 容器内?"
echo "3. Gateway 是否可以通过 HTTPS 访问?"
echo ""
echo "=========================================="